languageCode = 'en-us'
baseURL = "https://pnp.github.io/blog"
title = "Microsoft 365 Community Blog"

# Set content editor
newContentEditor = "code"
timeout = 60000

[frontmatter]
date = ['date', 'publishDate', 'lastmod']
expiryDate = ['expiryDate']
lastmod = [':git', 'lastmod', 'date', 'publishDate']
publishDate = ['publishDate', 'date']